const electricalEngineeringCourseRequirementsURLs = [
    'https://catalog.gatech.edu/programs/signal-information-processing-robotics-autonomous-systems-electrical-engineering-bs/',
    'https://catalog.gatech.edu/programs/signal-information-processing-telecommunications-electrical-engineering-bs/',
    'https://catalog.gatech.edu/programs/signal-information-processing-electronic-devices-electrical-engineering-bs/',
    'https://catalog.gatech.edu/programs/electric-energy-systems-signal-information-processing-electrical-engineering-bs/',
    'https://catalog.gatech.edu/programs/signal-information-processing-circuit-technology-electrical-engieering-bs/',
    'https://catalog.gatech.edu/programs/signal-information-processing-bioengineering-electrical-engineering-bs/',
    'https://catalog.gatech.edu/programs/signal-information-processing-sensing-exploration-electrical-engineering-bs/',
    'https://catalog.gatech.edu/programs/robotics-autonomous-systems-electronic-devices-electrical-engineering-bs/',
    'https://catalog.gatech.edu/programs/robotics-autonomous-systems-circuit-technology-electrical-engineering-bs/',
    'https://catalog.gatech.edu/programs/electric-energy-systems-robotics-autonomous-systems-electrical-engineering-bs/',
    'https://catalog.gatech.edu/programs/robotics-autonomous-systems-bioengineering-electrical-engineering-bs/',
    'https://catalog.gatech.edu/programs/robotics-autonomous-systems-sensing-exploration-electrical-engineering-bs/',
    'https://catalog.gatech.edu/programs/robotics-autonomous-systems-telecommunications-electrical-engineering-bs/',
    'https://catalog.gatech.edu/programs/electric-energy-systems-telecommunications-electrical-engineering-bs/',
    'https://catalog.gatech.edu/programs/telecommunications-bioengineering-electrical-engineering-bs/',
    'https://catalog.gatech.edu/programs/telecommunications-sensing-exploration-electrical-engineering-bs/',
    'https://catalog.gatech.edu/programs/electric-energy-systems-electronic-devices-electrical-engineering-bs/index.html',
    'https://catalog.gatech.edu/programs/electronic-devices-circuit-technology-electrical-engineering-bs/',
    'https://catalog.gatech.edu/programs/electronic-devices-bioengineering-electrical-engineering-bs/',
    'https://catalog.gatech.edu/programs/electronic-devices-sensing-exploration-electrical-engineering-bs/',
    'https://catalog.gatech.edu/programs/telecommunications-electronic-devices-electrical-engineering-bs/',
    'https://catalog.gatech.edu/programs/electric-energy-systems-circuit-technology-electrical-engineering-bs/',
    'https://catalog.gatech.edu/programs/circuit-technology-bioengineering-electrical-engineering-bs/',
    'https://catalog.gatech.edu/programs/circuit-technology-sensing-exploration-electrical-engineering-bs/',
    'https://catalog.gatech.edu/programs/telecommunications-circuit-technology-electrical-engineering-bs/',
    'https://catalog.gatech.edu/programs/electric-energy-systems-bioengineering-electrical-engineering-bs/',
    'https://catalog.gatech.edu/programs/bioengineering-sensing-exploration-electrical-engineering-bs/',
    'https://catalog.gatech.edu/programs/electric-energy-systems-sensing-exploration-electrical-engineering-bs/',
];

const computerEngineeringCourseRequirementsURLs = [
    'https://catalog.gatech.edu/programs/cybersecurity-distributed-system-software-design-computer-engineering-bs/',
    'https://catalog.gatech.edu/programs/cybersecurity-computing-hardware-emerging-architectures-computer-engineering-bs/',
    'https://catalog.gatech.edu/programs/cybersecurity-signal-information-processing-computer-engineering-bs/',
    'https://catalog.gatech.edu/programs/cybersecurity-telecommunications-computer-engineering-bs/',
    'https://catalog.gatech.edu/programs/cybersecurity-robotics-autonomous-systems-computer-engineering-bs/',
    'https://catalog.gatech.edu/programs/cybersecurity-systems-architecture-computer-engineering-bs/',
    'https://catalog.gatech.edu/programs/cybersecurity-devices-computer-engineering-bs/',
    'https://catalog.gatech.edu/programs/cybersecurity-information-internetworks-computer-engineering-bs/',
    'https://catalog.gatech.edu/programs/computing-hardware-emerging-architectures-signal-information-processing-computer-engineering-bs/',
    'https://catalog.gatech.edu/programs/computing-hardware-emerging-architectures-telecommunications-computer-engineering-bs/',
    'https://catalog.gatech.edu/programs/computing-hardware-emerging-architectures-robotics-autonomous-systems-computer-engineering-bs/',
    'https://catalog.gatech.edu/programs/computing-hardware-emerging-architectures-systems-architecture-computer-engineering-bs/',
    'https://catalog.gatech.edu/programs/computing-hardware-emerging-architectures-devices-computer-engineering-bs/',
    'https://catalog.gatech.edu/programs/computing-hardware-emerging-architectures-information-internetworks-computer-engineering-bs/',
    'https://catalog.gatech.edu/programs/distributed-system-software-design-telecommunications-computer-engineering-bs/',
    'https://catalog.gatech.edu/programs/distributed-system-software-design-systems-architecture-computer-engineering-bs/',
    'https://catalog.gatech.edu/programs/distributed-system-software-design-signal-information-processing-computer-engineering-bs/',
    'https://catalog.gatech.edu/programs/distributed-system-software-design-robotics-autonomous-systems-computer-engineering-bs/',
    'https://catalog.gatech.edu/programs/distributed-system-software-design-information-internetworks-computer-engineering-bs/',
    'https://catalog.gatech.edu/programs/distributed-system-software-design-computing-hardware-emerging-architectures-computer-engineering-bs/',
    'https://catalog.gatech.edu/programs/distributed-system-software-design-devices-computer-engineering-bs/',
];

const electricalEngineeringFourYearPlanURLs = [
    'https://ece.gatech.edu/sites/default/files/documents/undergraduate/curriculum-threads/ee/bioees.pdf',
    'https://ece.gatech.edu/sites/default/files/documents/undergraduate/curriculum-threads/ee/biosens.pdf',
    'https://ece.gatech.edu/sites/default/files/documents/undergraduate/curriculum-threads/ee/ctechbio.pdf',
    'https://ece.gatech.edu/sites/default/files/documents/undergraduate/curriculum-threads/ee/ctechees.pdf',
    'https://ece.gatech.edu/sites/default/files/documents/undergraduate/curriculum-threads/ee/ctechsens.pdf',
    'https://ece.gatech.edu/sites/default/files/documents/undergraduate/curriculum-threads/ee/edevbio.pdf',
    'https://ece.gatech.edu/sites/default/files/documents/undergraduate/curriculum-threads/ee/edevctech.pdf',
    'https://ece.gatech.edu/sites/default/files/documents/undergraduate/curriculum-threads/ee/edevees.pdf',
    'https://ece.gatech.edu/sites/default/files/documents/undergraduate/curriculum-threads/ee/edevsens.pdf',
    'https://ece.gatech.edu/sites/default/files/documents/undergraduate/curriculum-threads/ee/eessens.pdf', // Note: this one is not formatted like the rest. It will not work.
    'https://ece.gatech.edu/sites/default/files/documents/undergraduate/curriculum-threads/ee/robbio.pdf',
    'https://ece.gatech.edu/sites/default/files/documents/undergraduate/curriculum-threads/ee/robctech.pdf',
    'https://ece.gatech.edu/sites/default/files/documents/undergraduate/curriculum-threads/ee/robedev.pdf',
    'https://ece.gatech.edu/sites/default/files/documents/undergraduate/curriculum-threads/ee/robees.pdf',
    'https://ece.gatech.edu/sites/default/files/documents/undergraduate/curriculum-threads/ee/robsens.pdf',
    'https://ece.gatech.edu/sites/default/files/documents/undergraduate/curriculum-threads/ee/robtele.pdf',
    'https://ece.gatech.edu/sites/default/files/documents/undergraduate/curriculum-threads/ee/sipbio.pdf',
    'https://ece.gatech.edu/sites/default/files/documents/undergraduate/curriculum-threads/ee/sipctech.pdf',
    'https://ece.gatech.edu/sites/default/files/documents/undergraduate/curriculum-threads/ee/sipedev.pdf',
    'https://ece.gatech.edu/sites/default/files/documents/undergraduate/curriculum-threads/ee/sipees.pdf',
    'https://ece.gatech.edu/sites/default/files/documents/undergraduate/curriculum-threads/ee/siprob.pdf',
    'https://ece.gatech.edu/sites/default/files/documents/undergraduate/curriculum-threads/ee/sipsens.pdf',
    'https://ece.gatech.edu/sites/default/files/documents/undergraduate/curriculum-threads/ee/siptele.pdf',
    'https://ece.gatech.edu/sites/default/files/documents/undergraduate/curriculum-threads/ee/telebio.pdf',
    'https://ece.gatech.edu/sites/default/files/documents/undergraduate/curriculum-threads/ee/telectech.pdf',
    'https://ece.gatech.edu/sites/default/files/documents/undergraduate/curriculum-threads/ee/teleedev.pdf',
    'https://ece.gatech.edu/sites/default/files/documents/undergraduate/curriculum-threads/ee/teleees.pdf',
    'https://ece.gatech.edu/sites/default/files/documents/undergraduate/curriculum-threads/ee/telesens.pdf',
];

const computerEngineeringFourYearPlanURLs = [
    'https://ece.gatech.edu/sites/default/files/documents/undergraduate/curriculum-threads/cmpe/eightsemesterplanspdf_cmpechea_infint.pdf',
    'https://ece.gatech.edu/sites/default/files/documents/undergraduate/curriculum-threads/cmpe/eightsemesterplanspdf_cmpechea_rob.pdf',
    'https://ece.gatech.edu/sites/default/files/documents/undergraduate/curriculum-threads/cmpe/eightsemesterplanspdf_cmpechea_sip.pdf',
    'https://ece.gatech.edu/sites/default/files/documents/undergraduate/curriculum-threads/cmpe/eightsemesterplanspdf_cmpechea_sysarch.pdf',
    'https://ece.gatech.edu/sites/default/files/documents/undergraduate/curriculum-threads/cmpe/eightsemesterplanspdf_cmpechea_telecom.pdf',
    'https://ece.gatech.edu/sites/default/files/documents/undergraduate/curriculum-threads/cmpe/eightsemesterplanspdf_cmpecyber_chea.pdf',
    'https://ece.gatech.edu/sites/default/files/documents/undergraduate/curriculum-threads/cmpe/eightsemesterplanspdf_cmpecyber_devices.pdf',
    'https://ece.gatech.edu/sites/default/files/documents/undergraduate/curriculum-threads/cmpe/eightsemesterplanspdf_cmpecyber_dssd.pdf',
    'https://ece.gatech.edu/sites/default/files/documents/undergraduate/curriculum-threads/cmpe/eightsemesterplanspdf_cmpecyber_infint.pdf',
    'https://ece.gatech.edu/sites/default/files/documents/undergraduate/curriculum-threads/cmpe/eightsemesterplanspdf_cmpecyber_rob.pdf',
    'https://ece.gatech.edu/sites/default/files/documents/undergraduate/curriculum-threads/cmpe/eightsemesterplanspdf_cmpecyber_sip.pdf',
    'https://ece.gatech.edu/sites/default/files/documents/undergraduate/curriculum-threads/cmpe/eightsemesterplanspdf_cmpecyber_sysarch.pdf',
    'https://ece.gatech.edu/sites/default/files/documents/undergraduate/curriculum-threads/cmpe/eightsemesterplanspdf_cmpecyber_telecom.pdf',
    'https://ece.gatech.edu/sites/default/files/documents/undergraduate/curriculum-threads/cmpe/eightsemesterplanspdf_cmpedsdd_chea.pdf',
    'https://ece.gatech.edu/sites/default/files/documents/undergraduate/curriculum-threads/cmpe/eightsemesterplanspdf_cmpedsdd_devices_.pdf',
    'https://ece.gatech.edu/sites/default/files/documents/undergraduate/curriculum-threads/cmpe/eightsemesterplanspdf_cmpedsdd_infint.pdf',
    'https://ece.gatech.edu/sites/default/files/documents/undergraduate/curriculum-threads/cmpe/eightsemesterplanspdf_cmpedsdd_rob.pdf',
    'https://ece.gatech.edu/sites/default/files/documents/undergraduate/curriculum-threads/cmpe/eightsemesterplanspdf_cmpedsdd_sip.pdf',
    'https://ece.gatech.edu/sites/default/files/documents/undergraduate/curriculum-threads/cmpe/eightsemesterplanspdf_cmpedsdd_sysarch.pdf',
    'https://ece.gatech.edu/sites/default/files/documents/undergraduate/curriculum-threads/cmpe/eightsemesterplanspdf_cmpedsdd_telecom.pdf',
    'https://ece.gatech.edu/sites/default/files/documents/undergraduate/curriculum-threads/cmpe/eightsemesterplanspdf_cmpechea_devices_.pdf',
];

const computerEngineeringThreads = [
    'https://ece.gatech.edu/distributed-system-software-design',
    'https://ece.gatech.edu/cybersecurity-thread',
    'https://ece.gatech.edu/computing-hardware-emerging-architectures-thread',
    'https://ece.gatech.edu/information-internetworks-thread',
    'https://ece.gatech.edu/systems-architecture-thread',
    'https://ece.gatech.edu/robotics-autonomous-systems-thread',
    'https://ece.gatech.edu/telecommunications-thread',
    'https://ece.gatech.edu/academics/undergraduate/signal-information-processing-thread',
    'https://ece.gatech.edu/devices-thread',
];

const electricalEngineeringThreads = [
    'https://ece.gatech.edu/academics/undergraduate/signal-information-processing-thread',
    'https://ece.gatech.edu/robotics-autonomous-systems-thread',
    'https://ece.gatech.edu/bioengineering-thread',
    'https://ece.gatech.edu/ee-thread/telecommunications',
    'https://ece.gatech.edu/sensing-exploration-thread',
    'https://ece.gatech.edu/electric-energy-systems-thread',
    'https://ece.gatech.edu/electronic-optoelectronic-devices-thread',
    'https://ece.gatech.edu/circuit-technology-thread',
]



export {
    electricalEngineeringCourseRequirementsURLs,
    computerEngineeringCourseRequirementsURLs,
    electricalEngineeringFourYearPlanURLs,
    computerEngineeringFourYearPlanURLs,
    electricalEngineeringThreads,
};